### ISSUE TITLE
Indent guide improved

### ISSUE THREAD

**Issue by smlombardi** [Briles/gruvbox-atom#6]
Any thoughts on styling the colors use by the[ indent-guide-improved package](https://atom.io/packages/indent-guide-improved) to better mesh with the Gruvbox palette?

``` less
.indent-guide-improved {
  background-color: gray;
  &.indent-guide-stack {
    background-color: cyan;
    &.indent-guide-active {
      background-color: blue;
    }
  }
}
```
